wandb_version: 1

data.batch_size:
  value: 512
data.dphi_max:
  value: 0.012193355583173944
data.dz_max:
  value: 14.220353082111805
data.input_dir:
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/trigger/1/
data.input_dir2:
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/nontrigger/0/
data.n_folders:
  value: 2
data.n_mix:
  value: 20
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: hitgraphs_sparse_new
data.real_weight:
  value: 0.8963932690490587
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 4
model.input_dim:
  value: 5
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agnn
optimizer.beta_1:
  value: 0.5464134460203119
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 2.591805760079176e-06
optimizer.learning_rate:
  value: 0.002156142434795516
optimizer.learning_rate_decay_rate:
  value: 0.8503743727901918
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 1.5385752566084965e-07
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 12
