wandb_version: 1

data.batch_size:
  value: 512
data.input_dir:
  value: /ssd1/giorgian/hits-data-august-2022-ctypes/trigger/1/
data.input_dir2:
  value: /ssd1/giorgian/hits-data-august-2022-ctypes/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.use_cylindrical_std:
  value: true
data.use_hit_type:
  value: true
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: ReLU
model.hidden_dim:
  value: 128
model.input_dim:
  value: 9
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 5
model.name:
  value: agnn_trigger
optimizer.beta_1:
  value: 0.819645509779992
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 1.5828012531595012e-05
optimizer.learning_rate:
  value: 0.0004777229206692078
optimizer.learning_rate_decay_rate:
  value: 0.9754475108678816
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 3.1949059601455425e-07
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
