wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1724497538.484868
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.9
      8:
      - 5
data.batch_size:
  desc: null
  value: 64
data.construct_edges:
  desc: null
  value: false
data.input_dir:
  desc: null
  value: /ssd3/giorgian/hits-data-august-2024/trigger/1/
data.input_dir2:
  desc: null
  value: /ssd3/giorgian/hits-data-august-2024/nontrigger/1/
data.load_full_event:
  desc: null
  value: false
data.n_folders:
  desc: null
  value: 2
data.n_mix:
  desc: null
  value: 1
data.n_train:
  desc: null
  value: 250000
data.n_valid:
  desc: null
  value: 100000
data.n_workers:
  desc: null
  value: 16
data.name:
  desc: null
  value: hit_graph_trigger_pileup
data.phi_slope_max:
  desc: null
  value: 0.012193355583173944
data.real_weight:
  desc: null
  value: 1
data.use_intt:
  desc: null
  value: false
data.z0_max:
  desc: null
  value: 14.220353082111805
model.hidden_activation:
  desc: null
  value: PReLU
model.hidden_dim:
  desc: null
  value: 16
model.input_dim:
  desc: null
  value: 5
model.layer_norm:
  desc: null
  value: true
model.loss_func:
  desc: null
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  desc: null
  value: 1
model.name:
  desc: null
  value: garnet_trigger
optimizer.beta_1:
  desc: null
  value: 0.49750025795259206
optimizer.beta_2:
  desc: null
  value: 0.999
optimizer.eps:
  desc: null
  value: 4.293843626869477e-05
optimizer.learning_rate:
  desc: null
  value: 7.922921839786085e-05
optimizer.learning_rate_decay_rate:
  desc: null
  value: 0.9772876428711148
optimizer.name:
  desc: null
  value: Adam
optimizer.weight_decay:
  desc: null
  value: 0.00012630390926337136
output_dir:
  desc: null
  value: trigger_results/agnn/
trainer.name:
  desc: null
  value: gnn_trigger
training.n_total_epochs:
  desc: null
  value: 12
