wandb_version: 1

data.batch_size:
  value: 512
data.input_dir:
  value: /ssd1/giorgian/hits-data-march-2024/trigger/1/
data.input_dir2:
  value: /ssd1/giorgian/hits-data-august-2022-ctypes/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_train:
  value: 40000
data.n_valid:
  value: 9000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.use_cylindrical_std:
  value: false
data.use_hit_type:
  value: false
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 8
model.input_dim:
  value: 5
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agnn_trigger
optimizer.beta_1:
  value: 0.6725857351094955
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 1.3719379336458088e-06
optimizer.learning_rate:
  value: 0.0003074566670692615
optimizer.learning_rate_decay_rate:
  value: 0.8365376569473432
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 6.918464482191013e-06
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
