_wandb:
    value:
        cli_version: 0.17.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 51
                - 53
                - 55
                - 77
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.2
            "5": 0.17.7
            "8":
                - 5
            "12": 0.17.7
            "13": linux-x86_64
data.batch_size:
    value: 12
data.construct_edges:
    value: true
data.input_dir:
    value: /ssd3/giorgian/hits-data-march-2024/trigger/1/
data.input_dir2:
    value: /ssd2/giorgian/hits-data-august-2022/nontrigger/0/
data.load_full_event:
    value: false
data.n_folders:
    value: 2
data.n_mix:
    value: 10
data.n_train:
    value: 800000
data.n_valid:
    value: 175000
data.n_workers:
    value: 16
data.name:
    value: hit_graph_trigger_pileup
data.phi_slope_max:
    value: 0.012193355583173944
data.real_weight:
    value: 1
data.use_intt:
    value: false
data.z0_max:
    value: 14.220353082111805
model.hidden_activation:
    value: PReLU
model.hidden_dim:
    value: 16
model.input_dim:
    value: 5
model.layer_norm:
    value: true
model.loss_func:
    value: binary_cross_entropy_with_logits
model.n_graph_iters:
    value: 1
model.name:
    value: agat_trigger
optimizer.beta_1:
    value: 0.894057666328759
optimizer.beta_2:
    value: 0.999
optimizer.eps:
    value: 0.00018161413173763285
optimizer.learning_rate:
    value: 0.0002753140055490911
optimizer.learning_rate_decay_rate:
    value: 0.7507282391152701
optimizer.name:
    value: Adam
optimizer.weight_decay:
    value: 1.340561003924377e-07
output_dir:
    value: trigger_results/agnn/
trainer.name:
    value: gnn_trigger
training.n_total_epochs:
    value: 12
