wandb_version: 1

data.batch_size:
  value: 64
data.construct_edges:
  value: false
data.input_dir:
  value: /ssd3/giorgian/hits-data-january-2024-yasser/trigger/events/
data.input_dir2:
  value: /ssd3/giorgian/hits-data-january-2024-yasser/nontrigger/events/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_mix:
  value: 1
data.n_train:
  value: 24300
data.n_valid:
  value: 10000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger_pileup
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.use_intt:
  value: true
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 64
model.input_dim:
  value: 5
model.layer_norm:
  value: true
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: garnet_trigger
optimizer.beta_1:
  value: 0.7549339394499103
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.0003686768782825968
optimizer.learning_rate:
  value: 0.007125213423351373
optimizer.learning_rate_decay_rate:
  value: 0.9380775335324568
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 3.697673155425536e-07
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
