wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.001467930194956174
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.3570340463190198
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 4.4468224730610865e-05
optimizer.finetune_factor:
  value: 2.3454545370400987e-09
optimizer.learning_rate:
  value: 0.00013204352313567362
optimizer.learning_rate_decay_rate:
  value: 0.9717004473551946
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 5.5598940196894343e-05
output_dir:
  value: train_results/cluster-gat/
