wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.00241267143036909
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.5047172760725998
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.0003892635074227253
optimizer.finetune_factor:
  value: 1.7846414160235758e-06
optimizer.learning_rate:
  value: 0.003138697796468642
optimizer.learning_rate_decay_rate:
  value: 0.8866795291315089
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 7.142195688892e-07
output_dir:
  value: train_results/cluster-gat/
