wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.004372257105018741
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.2575883470636237
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 7.035650366647902e-06
optimizer.finetune_factor:
  value: 7.872939178980344e-11
optimizer.learning_rate:
  value: 7.167433364643844e-05
optimizer.learning_rate_decay_rate:
  value: 0.8271768573534484
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 0.0007185814925912704
output_dir:
  value: train_results/cluster-gat/
