wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.002359769046790882
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.30949025232639676
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.0016604052453757757
optimizer.finetune_factor:
  value: 2.7625805208275835e-06
optimizer.learning_rate:
  value: 0.002995826928301314
optimizer.learning_rate_decay_rate:
  value: 0.8624641842668632
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 4.4246293848301014e-06
output_dir:
  value: train_results/cluster-gat/
