wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.0050888396535670654
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.9765899165659188
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.0004960696108423393
optimizer.finetune_factor:
  value: 2.1483774845462046e-06
optimizer.learning_rate:
  value: 0.0044982489089471995
optimizer.learning_rate_decay_rate:
  value: 0.9300126502120638
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 4.41073055809704e-05
output_dir:
  value: train_results/cluster-gat/
