wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.006817298551895487
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.9611558756169992
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.001329317302452135
optimizer.finetune_factor:
  value: 1.4913151117030651e-09
optimizer.learning_rate:
  value: 8.852763528039951e-05
optimizer.learning_rate_decay_rate:
  value: 0.8159313224206229
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 0.0001476951127678024
output_dir:
  value: train_results/cluster-gat/
