wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.005302291956526457
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.3390119663845704
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 7.443684268826983e-08
optimizer.finetune_factor:
  value: 2.5907403837072433e-08
optimizer.learning_rate:
  value: 0.00021128308082134383
optimizer.learning_rate_decay_rate:
  value: 0.7565403685234479
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 0.00019165864875561923
output_dir:
  value: train_results/cluster-gat/
