wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.006865833078680228
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.48645496127052495
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.00017504109337340037
optimizer.finetune_factor:
  value: 9.782488510314224e-05
optimizer.learning_rate:
  value: 0.0012753357618784692
optimizer.learning_rate_decay_rate:
  value: 0.9842781966999994
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 5.844135068984315e-06
output_dir:
  value: train_results/cluster-gat/
