wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.009458446672941417
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.30061106225140066
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 7.101667068024024e-05
optimizer.finetune_factor:
  value: 1.2958287748640542e-06
optimizer.learning_rate:
  value: 7.407767774869265e-05
optimizer.learning_rate_decay_rate:
  value: 0.9477023694269804
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 1.6587743846852687e-05
output_dir:
  value: train_results/cluster-gat/
