wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.0024506911143193856
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.2842020259464499
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 5.176167178909885e-06
optimizer.finetune_factor:
  value: 3.8652075637681185e-11
optimizer.learning_rate:
  value: 0.00040009345590271697
optimizer.learning_rate_decay_rate:
  value: 0.9106691024985888
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 1.52558422815584e-05
output_dir:
  value: train_results/cluster-gat/
