wandb_version: 1

data.batch_size:
  value: 256
data.max_radius:
  value: 0.007170086731031164
data.n_test:
  value: 100000
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: pixel_graph
data.nontrigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/nontrigger/0
data.trigger_input_dir:
  value: /ssd2/giorgian/pixels-data-august-2022/trigger/1/
epochs:
  value: 16
model.hidden_dim:
  value: 64
model.input_dim:
  value: 3
model.name:
  value: gat
optimizer.beta_1:
  value: 0.2631543286655085
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 4.41771387490101e-06
optimizer.finetune_factor:
  value: 3.3620005403112193e-12
optimizer.learning_rate:
  value: 0.00018708158080308208
optimizer.learning_rate_decay_rate:
  value: 0.8295361254770255
optimizer.type:
  value: Adam
optimizer.weight_decay:
  value: 3.1594750801886966e-05
output_dir:
  value: train_results/cluster-gat/
