wandb_version: 1

data.batch_size:
  value: 512
data.input_dir:
  value: /ssd1/giorgian/hits-data-march-2024/trigger/1/
data.input_dir2:
  value: /ssd1/giorgian/hits-data-august-2022-ctypes/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_train:
  value: 800000
data.n_valid:
  value: 175000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.use_cylindrical_std:
  value: false
data.use_hit_type:
  value: false
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 221
model.input_dim:
  value: 5
model.layer_norm:
  value: true
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agat_trigger
optimizer.beta_1:
  value: 0.8746860491384668
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.0001212089796681011
optimizer.learning_rate:
  value: 6.682752320660952e-05
optimizer.learning_rate_decay_rate:
  value: 0.90239997837875
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 2.0128517620347065e-05
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
