wandb_version: 1

data.batch_size:
  value: 12
data.construct_edges:
  value: false
data.drop_l1:
  value: false
data.drop_l2:
  value: true
data.drop_l3:
  value: true
data.input_dir:
  value: /ssd3/giorgian/hits-data-march-2024/trigger/1/
data.input_dir2:
  value: /ssd2/giorgian/hits-data-august-2022/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_mix:
  value: 10
data.n_train:
  value: 800000
data.n_valid:
  value: 175000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger_pileup
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 178
model.input_dim:
  value: 5
model.layer_norm:
  value: true
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: garnet_trigger
optimizer.beta_1:
  value: 0.6040719202811586
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 1.2806172761064129e-07
optimizer.learning_rate:
  value: 0.00024453328422295015
optimizer.learning_rate_decay_rate:
  value: 0.9388615053451644
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 1.11609993825288e-05
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
