wandb_version: 1

data.batch_size:
  value: 512
data.input_dir:
  value: /ssd1/giorgian/hits-data-march-2024/trigger/1/
data.input_dir2:
  value: /ssd1/giorgian/hits-data-august-2022-ctypes/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_train:
  value: 13000
data.n_valid:
  value: 20000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.use_cylindrical_std:
  value: false
data.use_hit_type:
  value: false
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: ReLU
model.hidden_dim:
  value: 249
model.input_dim:
  value: 5
model.layer_norm:
  value: true
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 4
model.name:
  value: agnn_trigger
optimizer.beta_1:
  value: 0.6638831433250277
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 2.3577650282927903e-05
optimizer.learning_rate:
  value: 0.003870747768119908
optimizer.learning_rate_decay_rate:
  value: 0.97615820876893
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 6.105814800672066e-07
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
