wandb_version: 1

data.batch_size:
  value: 512
data.dphi_max:
  value: 0.012193355583173944
data.dz_max:
  value: 14.220353082111805
data.input_dir:
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/trigger/1/
data.input_dir2:
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/nontrigger/0/
data.n_folders:
  value: 2
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: hitgraphs_sparse_new
data.real_weight:
  value: 0.04563183235076307
model.hidden_activation:
  value: ReLU
model.hidden_dim:
  value: 7
model.input_dim:
  value: 5
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agnn
optimizer.beta_1:
  value: 0.8938678785371488
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 5.855175907269004e-07
optimizer.learning_rate:
  value: 7.850715600308729e-05
optimizer.learning_rate_decay_rate:
  value: 0.7579429840291692
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 0.0003161137426754649
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 12
