wandb_version: 1

data.batch_size:
  value: 512
data.dphi_max:
  value: 0.012193355583173944
data.dz_max:
  value: 14.220353082111805
data.input_dir:
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/trigger/1/
data.input_dir2:
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/nontrigger/0/
data.n_folders:
  value: 2
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: hitgraphs_sparse_new
data.real_weight:
  value: 1.9635233739343727
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 7
model.input_dim:
  value: 5
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agnn
optimizer.beta_1:
  value: 0.25515302948592566
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 6.775976740667929e-08
optimizer.learning_rate:
  value: 0.00010961406392441384
optimizer.learning_rate_decay_rate:
  value: 0.8424150695511461
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 0.00034970124555607467
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 12
