wandb_version: 1

data.batch_size:
  value: 12
data.construct_edges:
  value: true
data.input_dir:
  value: /ssd3/giorgian/hits-data-august-2022-bp/trigger/1/
data.input_dir2:
  value: /ssd3/giorgian/hits-data-august-2022-bp/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_mix:
  value: 20
data.n_train:
  value: 20000
data.n_valid:
  value: 2000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger_pileup_bp
data.phi_slope_max:
  value: 0.012193355583173944
data.ramp_up_nmix:
  value: false
data.real_weight:
  value: 1
data.trigger_edge_weight:
  value: 10
data.use_intt:
  value: true
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 64
model.input_dim:
  value: 10
model.layer_norm:
  value: true
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 3
model.name:
  value: agnn
optimizer.beta_1:
  value: 0.25658453945605947
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 1.715601118654766e-07
optimizer.learning_rate:
  value: 0.0018988434703026032
optimizer.learning_rate_decay_rate:
  value: 0.7636307809576857
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 4.457449974708002e-06
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 7
