classifier_config: train_results/biatt-augment-adj/experiment_2023-06-13_10:12:01/config.pkl
classifier_checkpoint_file_path: train_results/biatt-augment-adj/experiment_2023-06-13_10:12:01/checkpoints/model_checkpoint_016.pth.tar
output_dir: train_results/biatt-explain/
wandb:
  project_name: physics-trigger
  run_name: biatt-blri
  tags: ["biatt", "blri", "loopy", "layernorm", "batchnorm", "prelu"]

loss: 
  alpha: 0.001
  beta: 0.001
  drop_epoch_start: 5
  #beta: 10

epochs: 10
finetune_epochs: 10
optimizer:
  finetune_factor: 0.00000000165554383046
  type: Adam
  learning_rate: 0.001
  beta_1: 0.7650424449768395
  beta_2: 0.999
  eps: 0.00003891674021588362
  weight_decay: 0.00001892968038142768
  learning_rate_decay_rate: 0.9

model_mod: 1
model:
  num_features: 37
  # 1 + 3 + 3 + 1 + 1 + 1 + 3
  # trigger_track + origin_vertex + ip + ptypes + energy + momentums
  num_gt_features: 12
  layers_spec: [[64, 8], [64, 8], [64, 8]]
  ln: True
  bn: False
  latent_dim: 32
  aggregator_activation: softmax
  recalculate_hits_mean: True
  hidden_activation: PReLU
  cylindrical_coordinates: True

data:
        name: gt-trkvec-masked
        trigger_input_dir: /ssd2/giorgian/HFML-NewFiles-1/trigger/1/
        nontrigger_input_dir: /ssd2/giorgian/HFML-NewFiles-1/nontrigger/0/
          #trigger_input_dir: /ssd2/giorgian/HFMLNewFiles-hits/trigger/1/
          #nontrigger_input_dir: /ssd2/giorgian/HFMLNewFiles-hits/nontrigger/0/

        rescale_by_percentile: -1

        n_train: 5000 #00
        n_valid: 10000 #0
        n_test: 1000 #00
        batch_size: 512

        add_geo_features: True
        use_radius: True
        use_predicted_pz: True
        use_energy: False
        use_momentum: False
        use_center: True
        use_parallel_momentum: False

        use_physics_pred: False
        use_n_pixels: False
        use_n_hits: True
        load_complete_graph: False

        n_workers: 16
