output_dir: train_results/biatt-blri/
wandb:
  project_name: physics-trigger
  run_name: biatt-blri
  tags: ["biatt", "blri", "loopy", "layernorm", "batchnorm", "prelu"]

model:
  R: 0.01
  n_neighbors: 5
  weights: distance
  n_closest: 10000

data:
        name: gt-trkvec-masked
        trigger_input_dir: /ssd2/tingting/HFMLNewFiles-old-parsed/trigger/1/
        nontrigger_input_dir: /ssd2/tingting/HFMLNewFiles-old-parsed/nontrigger/0/

        n_train: 5000 #0 #0 #0
        n_valid: 100 #0 #0 #0 #0
        n_test: 100000
        batch_size: 1

        add_geo_features: True
        use_radius: True
        use_predicted_pz: True
        use_energy: False
        use_momentum: False
        use_transverse_momentum: False
        use_parallel_momentum: False

        use_physics_pred: False

        n_workers: 16
        load_complete_graph: False
