output_dir: train_results/biatt-blri/
wandb:
  project_name: physics-trigger
  run_name: biatt-blri
  tags: ["biatt", "blri", "loopy", "layernorm", "batchnorm", "prelu"]

loss: 
  mse_weight: 0.001
  adj_weight: 0.001
  tn_weight: 0.001
  #beta: 10

epochs: 20
finetune_epochs: 10
optimizer:
  finetune_factor: 0.00000000165554383046
  type: Adam
  learning_rate: 0.00008014451108346615
  beta_1: 0.7650424449768395
  beta_2: 0.999
  eps: 0.00003891674021588362
  weight_decay: 0.00001892968038142768
  learning_rate_decay_rate: 0.00008014451108346615

model_mod: 1
model:
  num_features: 37
  layers_spec: [[32, 8], [32, 8], [32, 8]]
  ln: True
  bn: False
  num_classes: 2
  aggregator_activation: softmax
  recalculate_hits_mean: True
  self_split: False
  hidden_activation: PReLU

data:
        name: tracks
          #trigger_input_dir: /ssd2/giorgian/HFML-NewFiles-1/trigger/1/
          #nontrigger_input_dir: /ssd2/giorgian/HFML-NewFiles-1/nontrigger/0/
          #trigger_input_dir: /ssd2/giorgian/HFMLNewFiles-hits/trigger/1/
          #nontrigger_input_dir: /ssd2/giorgian/HFMLNewFiles-hits/nontrigger/0/
          #trigger_input_dir: /ssd3/giorgian/tracks-data-mixed-1/trigger/1/
          #nontrigger_input_dir: /ssd3/giorgian/tracks-data-mixed-1/nontrigger/1/
          
          #trigger_input_dir: /ssd3/giorgian/hits-data-october-2024/trigger/1/
          #nontrigger_input_dir: /ssd2/giorgian/hits-data-august-2022/nontrigger/0/
          #trigger_input_dir: /ssd3/giorgian/pred-tracks-october-2024/trigger/1/
          #nontrigger_input_dir: /ssd3/giorgian/pred-tracks-october-2024/nontrigger/0/


        trigger_input_dir: /ssd3/giorgian/tracks-data-august-2022/trigger/1/
        nontrigger_input_dir: /ssd3/giorgian/tracks-data-august-2022/nontrigger/0/
        rescale_by_percentile: -1
          #noise_level: 0.005

          #use_true_edges: False
        n_train: 80000 #0
        n_valid: 20000 #0
        n_test: 20000 #00
        batch_size: 64

        use_geometric_features: True
        use_radius: True
        use_predicted_pz: True
        use_energy: False
        use_momentum: False
        use_center: True
        use_parallel_momentum: False

        use_n_pixels: False
        use_n_hits: True
          #drop_nontrigger_percentage: 0.5
          #fake_nontrigger_augment_prob: 0.5


        n_workers: 16
          #load_complete_graph: False
