wandb_version: 1

data.batch_size:
  value: 512
data.input_dir:
  value: /ssd2/giorgian/hits-data-august-2022/trigger/1/
data.input_dir2:
  value: /ssd2/giorgian/hits-data-august-2022/nontrigger/0/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 1
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: ReLU
model.hidden_dim:
  value: 5
model.input_dim:
  value: 5
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agnn_trigger
optimizer.beta_1:
  value: 0.5923370055735023
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 1.6316473184633875e-05
optimizer.learning_rate:
  value: 0.004704354388313598
optimizer.learning_rate_decay_rate:
  value: 0.9765856702754973
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 2.5484647362493757e-07
output_dir:
  value: trigger_results/agnn/
trainer.name:
  value: gnn_trigger
training.n_total_epochs:
  value: 12
