wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1690769635.802235
    t:
      1:
      - 1
      - 51
      - 55
      - 77
      2:
      - 1
      - 51
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.9
      8:
      - 5
data.batch_size:
  desc: null
  value: 32
data.dphi_max:
  desc: null
  value: 0.012193355583173944
data.dz_max:
  desc: null
  value: 14.220353082111805
data.input_dir:
  desc: null
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/trigger/1/
data.input_dir2:
  desc: null
  value: /ssd2/giorgian/HFMLNewFiles-hits-1/nontrigger/0/
data.intt_only:
  desc: null
  value: true
data.n_folders:
  desc: null
  value: 2
data.n_mix:
  desc: null
  value: 20
data.n_train:
  desc: null
  value: 500000
data.n_valid:
  desc: null
  value: 100000
data.n_workers:
  desc: null
  value: 16
data.name:
  desc: null
  value: hitgraphs_sparse_new
data.real_weight:
  desc: null
  value: 1.861438378876407
model.hidden_activation:
  desc: null
  value: PReLU
model.hidden_dim:
  desc: null
  value: 7
model.input_dim:
  desc: null
  value: 5
model.layer_norm:
  desc: null
  value: false
model.loss_func:
  desc: null
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  desc: null
  value: 1
model.name:
  desc: null
  value: agnn
optimizer.beta_1:
  desc: null
  value: 0.9175556421057118
optimizer.beta_2:
  desc: null
  value: 0.999
optimizer.eps:
  desc: null
  value: 2.696379127047711e-05
optimizer.learning_rate:
  desc: null
  value: 0.00017698886265855269
optimizer.learning_rate_decay_rate:
  desc: null
  value: 0.772434292631762
optimizer.name:
  desc: null
  value: Adam
optimizer.weight_decay:
  desc: null
  value: 0.0003589948930866058
output_dir:
  desc: null
  value: tracking_results/agnn/
trainer.name:
  desc: null
  value: gnn_sparse
training.n_total_epochs:
  desc: null
  value: 12
