output_dir: train_results/particlenet-laplace/
tensorboard_output_dir: runs/particlenet-laplace/

epochs: 30

optimizer:
  type: Adam
  momentum: 0.9
  weight_decay: 0.0001
  learning_rate: 0.001

model:
  type: particlenet-laplace
  input_dim: 15
  hidden_dim: 64
  hidden_activation: ReLU
  layer_norm: True
  affinity_loss: True
  affinity_loss_CE_weight: 1
  affinity_loss_Lp_weight: 0.000001
  affinity_loss_11_weight: 0.000001
  affinity_loss_frobenius_weight: 0.000001
  d_metric: intertrack #einsum
  pairwise_attention: True
  k: 16
  GNN_config:
    hidden_activation: ReLU
    layer_norm: True
    n_graph_iters: 3

data:
        name: gt-trkgraph-nomasked
        input_dir: /ssd2/tingting/HFMLNewFiles-old-parsed/trigger/1
        input_dir2: /ssd2/tingting/HFMLNewFiles-old-parsed/nontrigger/0
        n_train1: 500000
        n_valid1: 200000
        n_test1: 200000
        n_train2: 500000
        n_valid2: 200000
        n_test2: 200000
        add_geo_features: True
        use_radius: False
        use_pz: False
        use_pt: False
        use_predicted_pz: False
        batch_size: 256
        n_workers: 4
        load_complete_graph: False
