wandb_version: 1

data.batch_size:
  value: 24
data.construct_edges:
  value: true
data.input_dir:
  value: /ssd3/giorgian/hits-data-january-2024-yasser/trigger/events/
data.input_dir2:
  value: /ssd3/giorgian/hits-data-january-2024-yasser/nontrigger/events/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_mix:
  value: 20
data.n_train:
  value: 25000
data.n_valid:
  value: 5000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_bp
data.phi_slope_max:
  value: 0.012193355583173944
data.ramp_rate:
  value: 3
data.ramp_up_nmix:
  value: true
data.real_weight:
  value: 8.082093613126212
data.trigger_edge_weight:
  value: 10
data.use_intt:
  value: true
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 64
model.intt_input_dim:
  value: 10
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.mvtx_input_dim:
  value: 5
model.n_graph_iters:
  value: 3
model.name:
  value: garnet_tracking
optimizer.beta_1:
  value: 0.4345757777005512
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.0008463166432549044
optimizer.learning_rate:
  value: 7.574909915336405e-05
optimizer.learning_rate_decay_rate:
  value: 0.8143438830122585
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 0.0001256442822303737
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 18
