wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745965524
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.12.2
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
data.batch_size:
  desc: null
  value: 512
data.input_dir:
  desc: null
  value: /ssd3/giorgian/hits-data-august-2022-bp/trigger/1/
data.input_dir2:
  desc: null
  value: /ssd3/giorgian/hits-data-august-2022-bp/nontrigger/0/
data.load_full_event:
  desc: null
  value: false
data.n_folders:
  desc: null
  value: 2
data.n_train:
  desc: null
  value: 60000
data.n_valid:
  desc: null
  value: 10000
data.n_workers:
  desc: null
  value: 16
data.name:
  desc: null
  value: hit_graph_trigger
data.phi_slope_max:
  desc: null
  value: 0.012193355583173944
data.real_weight:
  desc: null
  value: 1
data.use_cylindrical_std:
  desc: null
  value: false
data.use_hit_type:
  desc: null
  value: false
data.use_n_pixels:
  desc: null
  value: false
data.z0_max:
  desc: null
  value: 14.220353082111805
model.hidden_activation:
  desc: null
  value: ReLU
model.hidden_dim:
  desc: null
  value: 16
model.input_dim:
  desc: null
  value: 4
model.layer_norm:
  desc: null
  value: true
model.loss_func:
  desc: null
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  desc: null
  value: 3
model.name:
  desc: null
  value: agnn_trigger
optimizer.beta_1:
  desc: null
  value: 0.29275094699056164
optimizer.beta_2:
  desc: null
  value: 0.999
optimizer.eps:
  desc: null
  value: 0.0007511321438916299
optimizer.learning_rate:
  desc: null
  value: 0.0002186097629628031
optimizer.learning_rate_decay_rate:
  desc: null
  value: 0.8738530282624396
optimizer.name:
  desc: null
  value: Adam
optimizer.weight_decay:
  desc: null
  value: 5.042811862832792e-06
output_dir:
  desc: null
  value: /disks/disk1/giorgian/old-trainings/trigger_results/trigger_results/agnn/
trainer.name:
  desc: null
  value: gnn_trigger
training.n_total_epochs:
  desc: null
  value: 12
