wandb_version: 1

data.batch_size:
  value: 12
data.construct_edges:
  value: false
data.input_dir:
  value: /ssd3/giorgian/hits-data-mixed/trigger/1/
data.input_dir2:
  value: /ssd3/giorgian/hits-data-mixed/nontrigger/1/
data.load_full_event:
  value: false
data.n_folders:
  value: 2
data.n_mix:
  value: 20
data.n_train:
  value: 800000
data.n_valid:
  value: 175000
data.n_workers:
  value: 16
data.name:
  value: hit_graph_trigger_pileup
data.phi_slope_max:
  value: 0.012193355583173944
data.ramp_rate:
  value: 3
data.ramp_up_nmix:
  value: true
data.real_weight:
  value: 1
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: PReLU
model.hidden_dim:
  value: 64
model.input_dim:
  value: 5
model.layer_norm:
  value: true
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 3
model.name:
  value: agnn
optimizer.beta_1:
  value: 0.6360410720055544
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 1.910504092757149e-07
optimizer.learning_rate:
  value: 0.0023350872497956148
optimizer.learning_rate_decay_rate:
  value: 0.7505658155326449
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 1.2983264578978629e-05
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 12
