_wandb:
    value:
        cli_version: 0.17.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 5
                - 51
                - 53
                - 55
                - 77
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.2
            "5": 0.17.7
            "8":
                - 5
            "12": 0.17.7
            "13": linux-x86_64
data.batch_size:
    value: 6
data.construct_edges:
    value: false
data.input_dir:
    value: /ssd3/giorgian/hits-data-mixed/trigger/1/
data.input_dir2:
    value: /ssd3/giorgian/hits-data-mixed/nontrigger/1/
data.load_full_event:
    value: false
data.n_folders:
    value: 2
data.n_mix:
    value: 20
data.n_train:
    value: 800000
data.n_valid:
    value: 175000
data.n_workers:
    value: 16
data.name:
    value: hit_graph_trigger_pileup
data.phi_slope_max:
    value: 0.012193355583173944
data.real_weight:
    value: 1
data.z0_max:
    value: 14.220353082111805
model.hidden_activation:
    value: PReLU
model.hidden_dim:
    value: 221
model.input_dim:
    value: 5
model.layer_norm:
    value: true
model.loss_func:
    value: binary_cross_entropy_with_logits
model.n_graph_iters:
    value: 1
model.name:
    value: garnet_trigger
optimizer.beta_1:
    value: 0.8746860491384668
optimizer.beta_2:
    value: 0.999
optimizer.eps:
    value: 0.0001212089796681011
optimizer.learning_rate:
    value: 6.682752320660952e-05
optimizer.learning_rate_decay_rate:
    value: 0.90239997837875
optimizer.name:
    value: Adam
optimizer.weight_decay:
    value: 2.0128517620347065e-05
output_dir:
    value: trigger_results/agnn/
trainer.name:
    value: gnn_trigger
training.n_total_epochs:
    value: 12
