wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1711672319.489616
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.9
      8:
      - 5
data.batch_size:
  desc: null
  value: 512
data.input_dir:
  desc: null
  value: /ssd1/giorgian/hits-data-march-2024/trigger/1/
data.input_dir2:
  desc: null
  value: /ssd1/giorgian/hits-data-august-2022-ctypes/nontrigger/0/
data.load_full_event:
  desc: null
  value: false
data.n_folders:
  desc: null
  value: 2
data.n_train:
  desc: null
  value: 13000
data.n_valid:
  desc: null
  value: 20000
data.n_workers:
  desc: null
  value: 16
data.name:
  desc: null
  value: hit_graph_trigger
data.phi_slope_max:
  desc: null
  value: 0.012193355583173944
data.real_weight:
  desc: null
  value: 1
data.use_cylindrical_std:
  desc: null
  value: false
data.use_hit_type:
  desc: null
  value: false
data.z0_max:
  desc: null
  value: 14.220353082111805
model.hidden_activation:
  desc: null
  value: ReLU
model.hidden_dim:
  desc: null
  value: 163
model.input_dim:
  desc: null
  value: 5
model.layer_norm:
  desc: null
  value: true
model.loss_func:
  desc: null
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  desc: null
  value: 3
model.name:
  desc: null
  value: agnn_trigger
optimizer.beta_1:
  desc: null
  value: 0.4164577759189588
optimizer.beta_2:
  desc: null
  value: 0.999
optimizer.eps:
  desc: null
  value: 0.00027475204288243064
optimizer.learning_rate:
  desc: null
  value: 0.00732344561728923
optimizer.learning_rate_decay_rate:
  desc: null
  value: 0.7837678141334775
optimizer.name:
  desc: null
  value: Adam
optimizer.weight_decay:
  desc: null
  value: 1.2035254042080457e-05
output_dir:
  desc: null
  value: trigger_results/agnn/
trainer.name:
  desc: null
  value: gnn_trigger
training.n_total_epochs:
  desc: null
  value: 12
