wandb_version: 1

data.batch_size:
  value: 128
data.input_dir:
  value: /ssd2/giorgian/hits-data-august-2022/trigger/1/
data.input_dir2:
  value: /ssd2/giorgian/hits-data-august-2022/nontrigger/0/
data.n_folders:
  value: 2
data.n_mix:
  value: 1
data.n_train:
  value: 500000
data.n_valid:
  value: 100000
data.n_workers:
  value: 16
data.name:
  value: hit_graph
data.phi_slope_max:
  value: 0.012193355583173944
data.real_weight:
  value: 0.1110713163027672
data.use_intt:
  value: false
data.z0_max:
  value: 14.220353082111805
model.hidden_activation:
  value: ReLU
model.hidden_dim:
  value: 8
model.input_dim:
  value: 5
model.layer_norm:
  value: false
model.loss_func:
  value: binary_cross_entropy_with_logits
model.n_graph_iters:
  value: 1
model.name:
  value: agnn
optimizer.beta_1:
  value: 0.7720593451515861
optimizer.beta_2:
  value: 0.999
optimizer.eps:
  value: 0.00017309749261671585
optimizer.learning_rate:
  value: 0.007737019292052513
optimizer.learning_rate_decay_rate:
  value: 0.7584261651359244
optimizer.name:
  value: Adam
optimizer.weight_decay:
  value: 1.477809694757765e-06
output_dir:
  value: tracking_results/agnn/
trainer.name:
  value: gnn_sparse
training.n_total_epochs:
  value: 12
