output_dir: tracking_results/train/

model_name_on_wandb: trigger-gnn

trainer:
    name: gnn_ip_2d

data:
    name: hit_graph_trigger_pileup
    # input_dir: /largehome/tingting/noise_removal/parsed_D0_Iteration6
    # input_dir2: /largehome/tingting/noise_removal/parsed_In_Iteration6
    # input_dir: /largehome/tingting/Data/parsed_data_allinfo/parsed_D0_Iteration6_allinfo
    # input_dir2: /largehome/tingting/Data/parsed_data_allinfo/parsed_In_Iteration6_allinfo
    #input_dir: /ssd1/giorgian/hits-data-august-2022-ctypes/trigger/1/
    input_dir: /secondssd/giorgian/hits-data-august-2024/trigger/1/
    input_dir2: /secondssd/giorgian/hits-data-august-2024/nontrigger/1/
    n_train: 250000
    n_valid: 40000 #0
    real_weight: 1
    batch_size: 12
    n_workers: 16
    n_folders: 2
    phi_slope_max: 0.012193355583173944
    z0_max: 14.220353082111805
    load_full_event: False
      #use_cylindrical_std: False
      #use_hit_type: False
    n_mix: 1
    use_intt: true
    construct_edges: false
    drop_l1: False
    drop_l2: False
    drop_l3: False
    intt_filter: False


model:
    name: garnet_ip
    input_dim: 5
    hidden_dim: 16
    hidden_activation: ReLU
    n_graph_iters: 1
    layer_norm: true
    loss_func: mse_loss
    add_n_hits: true
    #edge_model_path: /home1/giorgian/projects/trigger-detection-pipeline/sPHENIX/tracking_results/agnn/agnn-lr0.003402877625756795-b32-d8-ReLU-gi1-ln-False-n1000000/experiment_2024-05-12_10:28:01
    #node_model_path: /home1/giorgian/projects/trigger-detection-pipeline/sPHENIX/trigger_results/agnn/agnn-lr6.510991469352465e-05-b12-d195-PReLU-gi1-ln-True-n1600000/experiment_2024-06-14_21:00:31/

optimizer:
    name: Adam
    learning_rate: 0.0001
    weight_decay: 1.e-4
    lr_decay_schedule:
        - {start_epoch: 8, end_epoch: 16, factor: 0.1}
    beta_1: 0.9
    beta_2: 0.999
    eps: 1.0e-8

training:
    n_total_epochs: 16
