output_dir: /home1/tingtingxuan/trigger-detection-pipeline/tracking_result/tracking_hetero

model_name_on_wandb: tracking-gnn-fixcluster

trainer:
    name: gnn_sparse

data:
    name: hetero_hitgraphs_sparse
    # input_dir: /largehome/tingting/noise_removal/parsed_D0_Iteration6
    # input_dir2: /largehome/tingting/noise_removal/parsed_In_Iteration6
    # input_dir: /largehome/tingting/Data/parsed_data_allinfo/parsed_D0_Iteration6_allinfo
    # input_dir2: /largehome/tingting/Data/parsed_data_allinfo/parsed_In_Iteration6_allinfo
    # input_dir: /home1/tingtingxuan/Data/tracking_improve_attemp/new_parsed_data_sc/trigger
    # input_dir2: /home1/tingtingxuan/Data/tracking_improve_attemp/new_parsed_data_sc/nontrigger
    # input_dir: /home1/tingtingxuan/Data/parsed_7layer_hits_new/trigger
    # input_dir2: /home1/tingtingxuan/Data/parsed_7layer_hits_new/nontrigger
    # input_dir: /home1/tingtingxuan/Data/parsed_INTTclustered_hits/trigger
    # input_dir2: /home1/tingtingxuan/Data/parsed_INTTclustered_hits/nontrigger
    input_dir: /ssd1/giorgian/parsed-cluster-1.0/trigger
    input_dir2: /ssd1/giorgian/parsed-cluster-1.0/non-trigger
    n_train: 50000
    n_valid: 50000
    real_weight: 1
    batch_size: 32
    n_workers: 8
    n_folders: 2

model:
    name: hetero_gnn
    input_dim: 5
    hidden_dim: 128
    hidden_activation: Tanh
    n_graph_iters: 8
    layer_norm: True
    loss_func: binary_cross_entropy

optimizer:
    name: Adam
    learning_rate: 0.0001
    weight_decay: 1.e-4
    lr_decay_schedule:
        - {start_epoch: 60, end_epoch: 128, factor: 0.1}

training:
    n_total_epochs: 128