model_name: Diffpool
output_dir: /largehome/tingting/trigger-detection/results/test
epochs: 10

model:
  hidden_dim: 60
  hidden_activation: Tanh
  layer_norm: True
  learning_rate: 0.0005
  lr_scheduler_decrease_rate: 0.995
  diff_pool_config:
    max_num_nodes: 100
    hidden_dim: 8
    embedding_dim: 8
    label_dim: 1
    num_layers: 2
    num_pooling: 2
    assign_hidden_dim: 8
    assign_ratio: 0.25
    linkpred: False

data:
    name: hits_loader
    input_dir: /largehome/tingting/tracking/tracking_result_without_noise_In
    # input_dir: ../prepare/scaled_hits_data/nontrigger-event/NN
    n_train: 60000 # 000 
    n_valid: 2000 # 00
    real_weight: 1
    false_weight: 1
    batch_size: 100
    n_input_dir: 2
    input_dir2: /largehome/tingting/tracking/tracking_result_without_noise_D0
    # input_dir3: ../prepare/hits_data/nontrigger-event/ND
    random_permutation: True
    n_train2: 60000 # 000 #00
    n_valid2: 2000 # 00 #00
    n_train3: 100 #00
    n_valid3: 100 #00