model_name: GraphPooling
output_dir: results/GNN_Diffpool_nhits/scaled_hits/NN_trigger_5
epochs: 100

model_name_on_wandb: GraphPooling_mixedA

model:
  learning_rate: 0.0005
  lr_scheduler_decrease_rate: 0.99
  GNN_config:
    input_dim: 4
    hidden_dim: 8
    hidden_activation: Tanh
    layer_norm: True
    n_graph_iters: 4
    # edgenet: False
  diff_pool_config:
    max_num_nodes: 100
    hidden_dim: 8
    embedding_dim: 8
    label_dim: 1
    num_layers: 2
    num_pooling: 2
    assign_hidden_dim: 8
    assign_dims_list: [16, 4]
    use_assign_dims: True
    linkpred: False

data:
    name: hits_loader
    input_dir: /superhome/tingtingxuan/Data/tracking_result_allinfo/tracking_result_with_noise_In_dim8
    # input_dir: ../prepare/scaled_hits_data/nontrigger-event/NN
    n_train: 200000 # 000 # 000 
    n_valid: 50000 # 00
    real_weight: 1
    false_weight: 1
    batch_size: 1000
    n_input_dir: 2
    input_dir2: /superhome/tingtingxuan/Data/tracking_result_allinfo/tracking_result_with_noise_D0_dim8
    # input_dir3: ../prepare/hits_data/nontrigger-event/ND
    random_permutation: True
    n_train2: 200000 #000 # 000 #00
    n_valid2: 50000 # 00 #00
    n_train3: 100 #00
    n_valid3: 100 #00